openapi: 3.0.1
info:
  title: Task Manager API
  description: Backend project for a task manager
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /tasks:
    get:
      tags:
        - task
      operationId: getTasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDto'
    post:
      tags:
        - task
      operationId: postTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDto'
    put:
      tags:
        - task
      operationId: putTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDto'
    patch:
      tags:
        - task
      operationId: patchTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDto'
  /tasks/{id}:
    delete:
      tags:
        - task
      operationId: deleteTask
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDto'
components:
  schemas:
    TaskDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        day:
          type: string
          format: date-time
        text:
          type: string
        reminder:
          type: boolean
